# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cc668d5c8a3248c8759d8037f94661b565b20df849be6d2c3af3f97ffed894c44edf72ef8daf8d3fa0d19b3898f313ece654ba199a3abba6741e181ecf780bf

test:
  secret_key_base: 2df73c5020ef7b4855aa5d0d01ffb547d17416c61d9180d82b14e64df18e0b6055c948fae11dd02265075fea476873539d7a1698c9eda7dc0ebd61a967b6ce00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
